import SearchBar from '@/components/search/SearchBar'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>별별부동산</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SearchBar />
        <h1>Will be implemented</h1>
      </main>
    </>
  )
}
